drivers: soc: qcom: Simplify the timerqueue code by using cached rbtrees * Follow upstream commit 0135fcb
Fixes:

../drivers/soc/qcom/event_timer.c:54:3: error: field designator 'head' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .head = RB_ROOT,
         ^
../drivers/soc/qcom/event_timer.c:55:3: error: field designator 'next' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')                                    .next = NULL,
         ^
2 errors generated.